<error errorId="955d0b5b-7dd1-4d1f-968d-8af5f7807b2e" host="CHENSHIYI-PC" type="System.OperationCanceledException" message="已取消该操作。" source="mscorlib" detail="System.OperationCanceledException: 已取消该操作。&#xD;&#xA;   在 System.Threading.CancellationToken.ThrowOperationCanceledException()&#xD;&#xA;   在 System.Threading.CancellationToken.ThrowIfCancellationRequested()&#xD;&#xA;   在 System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;&#xA;   在 System.Web.Http.Filters.ActionFilterAttribute.&lt;ExecuteActionFilterAsyncCore&gt;d__0.MoveNext()&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;&#xA;   在 System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;&#xA;   在 System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" time="2015-11-26T05:59:18.2681314Z" />